window.esdocSearchIndex = [
  [
    "jsonapi.js/src/modules/db.es6~db",
    "function/index.html#static-function-DB",
    "<span>DB</span> <span class=\"search-result-import-path\">jsonapi.js/src/modules/DB.es6</span>",
    "function"
  ],
  [
    "jsonapi.js/src/modules/link.es6~link",
    "class/src/modules/Link.es6~Link.html",
    "<span>Link</span> <span class=\"search-result-import-path\">jsonapi.js/src/modules/Link.es6</span>",
    "class"
  ],
  [
    "jsonapi.js/src/modules/pool.es6~pool",
    "class/src/modules/Pool.es6~Pool.html",
    "<span>Pool</span> <span class=\"search-result-import-path\">jsonapi.js/src/modules/Pool.es6</span>",
    "class"
  ],
  [
    "jsonapi.js/src/modules/restful.es6~restful",
    "class/src/modules/RESTful.es6~RESTful.html",
    "<span>RESTful</span> <span class=\"search-result-import-path\">jsonapi.js/src/modules/RESTful.es6</span>",
    "class"
  ],
  [
    "jsonapi.js/src/modules/relationship.es6~relationship",
    "class/src/modules/Relationship.es6~Relationship.html",
    "<span>Relationship</span> <span class=\"search-result-import-path\">jsonapi.js/src/modules/Relationship.es6</span>",
    "class"
  ],
  [
    "jsonapi.js/src/modules/resource.es6~resource",
    "class/src/modules/Resource.es6~Resource.html",
    "<span>Resource</span> <span class=\"search-result-import-path\">jsonapi.js/src/modules/Resource.es6</span>",
    "class"
  ],
  [
    "jsonapi.js/src/modules/resourceidentifier.es6~resourceidentifier",
    "class/src/modules/ResourceIdentifier.es6~ResourceIdentifier.html",
    "<span>ResourceIdentifier</span> <span class=\"search-result-import-path\">jsonapi.js/src/modules/ResourceIdentifier.es6</span>",
    "class"
  ],
  [
    "jsonapi.js/src/modules/response.es6~response",
    "class/src/modules/Response.es6~Response.html",
    "<span>Response</span> <span class=\"search-result-import-path\">jsonapi.js/src/modules/Response.es6</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/jsonapi.es6",
    "file/src/jsonapi.es6.html",
    "src/jsonapi.es6",
    "file"
  ],
  [
    "src/jsonapi.es6~metaobject",
    "typedef/index.html#static-typedef-MetaObject",
    "src/jsonapi.es6~MetaObject",
    "typedef"
  ],
  [
    "src/modules/db.es6",
    "file/src/modules/DB.es6.html",
    "src/modules/DB.es6",
    "file"
  ],
  [
    "src/modules/db.es6~lowdb",
    "external/index.html",
    "src/modules/DB.es6~LowDB",
    "external"
  ],
  [
    "src/modules/link.es6",
    "file/src/modules/Link.es6.html",
    "src/modules/Link.es6",
    "file"
  ],
  [
    "src/modules/link.es6~link#constructor",
    "class/src/modules/Link.es6~Link.html#instance-constructor-constructor",
    "src/modules/Link.es6~Link#constructor",
    "method"
  ],
  [
    "src/modules/link.es6~link#deserialize",
    "class/src/modules/Link.es6~Link.html#instance-method-deserialize",
    "src/modules/Link.es6~Link#deserialize",
    "method"
  ],
  [
    "src/modules/link.es6~link#href",
    "class/src/modules/Link.es6~Link.html#instance-member-href",
    "src/modules/Link.es6~Link#href",
    "member"
  ],
  [
    "src/modules/link.es6~link#meta",
    "class/src/modules/Link.es6~Link.html#instance-member-meta",
    "src/modules/Link.es6~Link#meta",
    "member"
  ],
  [
    "src/modules/link.es6~link#serialize",
    "class/src/modules/Link.es6~Link.html#instance-method-serialize",
    "src/modules/Link.es6~Link#serialize",
    "method"
  ],
  [
    "src/modules/link.es6~linkobject",
    "typedef/index.html#static-typedef-LinkObject",
    "src/modules/Link.es6~LinkObject",
    "typedef"
  ],
  [
    "src/modules/pool.es6",
    "file/src/modules/Pool.es6.html",
    "src/modules/Pool.es6",
    "file"
  ],
  [
    "src/modules/pool.es6~pool#addlinkage",
    "class/src/modules/Pool.es6~Pool.html#instance-method-addLinkage",
    "src/modules/Pool.es6~Pool#addLinkage",
    "method"
  ],
  [
    "src/modules/pool.es6~pool#addremote",
    "class/src/modules/Pool.es6~Pool.html#instance-method-addRemote",
    "src/modules/Pool.es6~Pool#addRemote",
    "method"
  ],
  [
    "src/modules/pool.es6~pool#constructor",
    "class/src/modules/Pool.es6~Pool.html#instance-constructor-constructor",
    "src/modules/Pool.es6~Pool#constructor",
    "method"
  ],
  [
    "src/modules/pool.es6~pool#create",
    "class/src/modules/Pool.es6~Pool.html#instance-method-create",
    "src/modules/Pool.es6~Pool#create",
    "method"
  ],
  [
    "src/modules/pool.es6~pool#db",
    "class/src/modules/Pool.es6~Pool.html#instance-member-db",
    "src/modules/Pool.es6~Pool#db",
    "member"
  ],
  [
    "src/modules/pool.es6~pool#fetch",
    "class/src/modules/Pool.es6~Pool.html#instance-method-fetch",
    "src/modules/Pool.es6~Pool#fetch",
    "method"
  ],
  [
    "src/modules/pool.es6~pool#get",
    "class/src/modules/Pool.es6~Pool.html#instance-method-get",
    "src/modules/Pool.es6~Pool#get",
    "method"
  ],
  [
    "src/modules/pool.es6~pool#getrelated",
    "class/src/modules/Pool.es6~Pool.html#instance-method-getRelated",
    "src/modules/Pool.es6~Pool#getRelated",
    "method"
  ],
  [
    "src/modules/pool.es6~pool#getremote",
    "class/src/modules/Pool.es6~Pool.html#instance-method-getRemote",
    "src/modules/Pool.es6~Pool#getRemote",
    "method"
  ],
  [
    "src/modules/pool.es6~pool#has",
    "class/src/modules/Pool.es6~Pool.html#instance-method-has",
    "src/modules/Pool.es6~Pool#has",
    "method"
  ],
  [
    "src/modules/pool.es6~pool#linkageoperation",
    "class/src/modules/Pool.es6~Pool.html#instance-method-linkageOperation",
    "src/modules/Pool.es6~Pool#linkageOperation",
    "method"
  ],
  [
    "src/modules/pool.es6~pool#remote",
    "class/src/modules/Pool.es6~Pool.html#instance-member-remote",
    "src/modules/Pool.es6~Pool#remote",
    "member"
  ],
  [
    "src/modules/pool.es6~pool#remove",
    "class/src/modules/Pool.es6~Pool.html#instance-method-remove",
    "src/modules/Pool.es6~Pool#remove",
    "method"
  ],
  [
    "src/modules/pool.es6~pool#removelinkage",
    "class/src/modules/Pool.es6~Pool.html#instance-method-removeLinkage",
    "src/modules/Pool.es6~Pool#removeLinkage",
    "method"
  ],
  [
    "src/modules/pool.es6~pool#replacelinkage",
    "class/src/modules/Pool.es6~Pool.html#instance-method-replaceLinkage",
    "src/modules/Pool.es6~Pool#replaceLinkage",
    "method"
  ],
  [
    "src/modules/pool.es6~pool#sync",
    "class/src/modules/Pool.es6~Pool.html#instance-member-sync",
    "src/modules/Pool.es6~Pool#sync",
    "member"
  ],
  [
    "src/modules/pool.es6~pool#update",
    "class/src/modules/Pool.es6~Pool.html#instance-method-update",
    "src/modules/Pool.es6~Pool#update",
    "method"
  ],
  [
    "src/modules/restful.es6",
    "file/src/modules/RESTful.es6.html",
    "src/modules/RESTful.es6",
    "file"
  ],
  [
    "src/modules/restful.es6~restful.ajaxsetup",
    "class/src/modules/RESTful.es6~RESTful.html#static-method-ajaxSetup",
    "src/modules/RESTful.es6~RESTful.ajaxSetup",
    "method"
  ],
  [
    "src/modules/restful.es6~restful.delete",
    "class/src/modules/RESTful.es6~RESTful.html#static-method-delete",
    "src/modules/RESTful.es6~RESTful.delete",
    "method"
  ],
  [
    "src/modules/restful.es6~restful.get",
    "class/src/modules/RESTful.es6~RESTful.html#static-method-get",
    "src/modules/RESTful.es6~RESTful.get",
    "method"
  ],
  [
    "src/modules/restful.es6~restful.head",
    "class/src/modules/RESTful.es6~RESTful.html#static-method-head",
    "src/modules/RESTful.es6~RESTful.head",
    "method"
  ],
  [
    "src/modules/restful.es6~restful.patch",
    "class/src/modules/RESTful.es6~RESTful.html#static-method-patch",
    "src/modules/RESTful.es6~RESTful.patch",
    "method"
  ],
  [
    "src/modules/restful.es6~restful.post",
    "class/src/modules/RESTful.es6~RESTful.html#static-method-post",
    "src/modules/RESTful.es6~RESTful.post",
    "method"
  ],
  [
    "src/modules/restful.es6~restful.put",
    "class/src/modules/RESTful.es6~RESTful.html#static-method-put",
    "src/modules/RESTful.es6~RESTful.put",
    "method"
  ],
  [
    "src/modules/relationship.es6",
    "file/src/modules/Relationship.es6.html",
    "src/modules/Relationship.es6",
    "file"
  ],
  [
    "src/modules/relationship.es6~linksobject",
    "typedef/index.html#static-typedef-LinksObject",
    "src/modules/Relationship.es6~LinksObject",
    "typedef"
  ],
  [
    "src/modules/relationship.es6~relationship#addlinkage",
    "class/src/modules/Relationship.es6~Relationship.html#instance-method-addLinkage",
    "src/modules/Relationship.es6~Relationship#addLinkage",
    "method"
  ],
  [
    "src/modules/relationship.es6~relationship#constructor",
    "class/src/modules/Relationship.es6~Relationship.html#instance-constructor-constructor",
    "src/modules/Relationship.es6~Relationship#constructor",
    "method"
  ],
  [
    "src/modules/relationship.es6~relationship#data",
    "class/src/modules/Relationship.es6~Relationship.html#instance-member-data",
    "src/modules/Relationship.es6~Relationship#data",
    "member"
  ],
  [
    "src/modules/relationship.es6~relationship#deserialize",
    "class/src/modules/Relationship.es6~Relationship.html#instance-method-deserialize",
    "src/modules/Relationship.es6~Relationship#deserialize",
    "method"
  ],
  [
    "src/modules/relationship.es6~relationship#links",
    "class/src/modules/Relationship.es6~Relationship.html#instance-member-links",
    "src/modules/Relationship.es6~Relationship#links",
    "member"
  ],
  [
    "src/modules/relationship.es6~relationship#meta",
    "class/src/modules/Relationship.es6~Relationship.html#instance-member-meta",
    "src/modules/Relationship.es6~Relationship#meta",
    "member"
  ],
  [
    "src/modules/relationship.es6~relationship#removelinkage",
    "class/src/modules/Relationship.es6~Relationship.html#instance-method-removeLinkage",
    "src/modules/Relationship.es6~Relationship#removeLinkage",
    "method"
  ],
  [
    "src/modules/relationship.es6~relationship#replacelinkage",
    "class/src/modules/Relationship.es6~Relationship.html#instance-method-replaceLinkage",
    "src/modules/Relationship.es6~Relationship#replaceLinkage",
    "method"
  ],
  [
    "src/modules/relationship.es6~relationship#serialize",
    "class/src/modules/Relationship.es6~Relationship.html#instance-method-serialize",
    "src/modules/Relationship.es6~Relationship#serialize",
    "method"
  ],
  [
    "src/modules/relationship.es6~relationshipobject",
    "typedef/index.html#static-typedef-RelationshipObject",
    "src/modules/Relationship.es6~RelationshipObject",
    "typedef"
  ],
  [
    "src/modules/relationship.es6~resourcelinkage",
    "typedef/index.html#static-typedef-ResourceLinkage",
    "src/modules/Relationship.es6~ResourceLinkage",
    "typedef"
  ],
  [
    "src/modules/resource.es6",
    "file/src/modules/Resource.es6.html",
    "src/modules/Resource.es6",
    "file"
  ],
  [
    "src/modules/resource.es6~fields",
    "external/index.html",
    "src/modules/Resource.es6~Fields",
    "external"
  ],
  [
    "src/modules/resource.es6~resource#attributes",
    "class/src/modules/Resource.es6~Resource.html#instance-member-attributes",
    "src/modules/Resource.es6~Resource#attributes",
    "member"
  ],
  [
    "src/modules/resource.es6~resource#constructor",
    "class/src/modules/Resource.es6~Resource.html#instance-constructor-constructor",
    "src/modules/Resource.es6~Resource#constructor",
    "method"
  ],
  [
    "src/modules/resource.es6~resource#deserialize",
    "class/src/modules/Resource.es6~Resource.html#instance-method-deserialize",
    "src/modules/Resource.es6~Resource#deserialize",
    "method"
  ],
  [
    "src/modules/resource.es6~resource#flatten",
    "class/src/modules/Resource.es6~Resource.html#instance-method-flatten",
    "src/modules/Resource.es6~Resource#flatten",
    "method"
  ],
  [
    "src/modules/resource.es6~resource#getidentifier",
    "class/src/modules/Resource.es6~Resource.html#instance-method-getIdentifier",
    "src/modules/Resource.es6~Resource#getIdentifier",
    "method"
  ],
  [
    "src/modules/resource.es6~resource#links",
    "class/src/modules/Resource.es6~Resource.html#instance-member-links",
    "src/modules/Resource.es6~Resource#links",
    "member"
  ],
  [
    "src/modules/resource.es6~resource#relationships",
    "class/src/modules/Resource.es6~Resource.html#instance-member-relationships",
    "src/modules/Resource.es6~Resource#relationships",
    "member"
  ],
  [
    "src/modules/resource.es6~resource#serialize",
    "class/src/modules/Resource.es6~Resource.html#instance-method-serialize",
    "src/modules/Resource.es6~Resource#serialize",
    "method"
  ],
  [
    "src/modules/resource.es6~resource#setattribute",
    "class/src/modules/Resource.es6~Resource.html#instance-method-setAttribute",
    "src/modules/Resource.es6~Resource#setAttribute",
    "method"
  ],
  [
    "src/modules/resource.es6~resource#setattributes",
    "class/src/modules/Resource.es6~Resource.html#instance-method-setAttributes",
    "src/modules/Resource.es6~Resource#setAttributes",
    "method"
  ],
  [
    "src/modules/resource.es6~resource#setrelationship",
    "class/src/modules/Resource.es6~Resource.html#instance-method-setRelationship",
    "src/modules/Resource.es6~Resource#setRelationship",
    "method"
  ],
  [
    "src/modules/resource.es6~resource#setrelationships",
    "class/src/modules/Resource.es6~Resource.html#instance-method-setRelationships",
    "src/modules/Resource.es6~Resource#setRelationships",
    "method"
  ],
  [
    "src/modules/resource.es6~resource#unsetattribute",
    "class/src/modules/Resource.es6~Resource.html#instance-method-unsetAttribute",
    "src/modules/Resource.es6~Resource#unsetAttribute",
    "method"
  ],
  [
    "src/modules/resource.es6~resource#unsetrelationship",
    "class/src/modules/Resource.es6~Resource.html#instance-method-unsetRelationship",
    "src/modules/Resource.es6~Resource#unsetRelationship",
    "method"
  ],
  [
    "src/modules/resource.es6~resourceobject",
    "typedef/index.html#static-typedef-ResourceObject",
    "src/modules/Resource.es6~ResourceObject",
    "typedef"
  ],
  [
    "src/modules/resourceidentifier.es6",
    "file/src/modules/ResourceIdentifier.es6.html",
    "src/modules/ResourceIdentifier.es6",
    "file"
  ],
  [
    "src/modules/resourceidentifier.es6~resourceidentifier#constructor",
    "class/src/modules/ResourceIdentifier.es6~ResourceIdentifier.html#instance-constructor-constructor",
    "src/modules/ResourceIdentifier.es6~ResourceIdentifier#constructor",
    "method"
  ],
  [
    "src/modules/resourceidentifier.es6~resourceidentifier#deserialize",
    "class/src/modules/ResourceIdentifier.es6~ResourceIdentifier.html#instance-method-deserialize",
    "src/modules/ResourceIdentifier.es6~ResourceIdentifier#deserialize",
    "method"
  ],
  [
    "src/modules/resourceidentifier.es6~resourceidentifier#id",
    "class/src/modules/ResourceIdentifier.es6~ResourceIdentifier.html#instance-member-id",
    "src/modules/ResourceIdentifier.es6~ResourceIdentifier#id",
    "member"
  ],
  [
    "src/modules/resourceidentifier.es6~resourceidentifier#serialize",
    "class/src/modules/ResourceIdentifier.es6~ResourceIdentifier.html#instance-method-serialize",
    "src/modules/ResourceIdentifier.es6~ResourceIdentifier#serialize",
    "method"
  ],
  [
    "src/modules/resourceidentifier.es6~resourceidentifier#type",
    "class/src/modules/ResourceIdentifier.es6~ResourceIdentifier.html#instance-member-type",
    "src/modules/ResourceIdentifier.es6~ResourceIdentifier#type",
    "member"
  ],
  [
    "src/modules/resourceidentifier.es6~resourceidentifierobject",
    "typedef/index.html#static-typedef-ResourceIdentifierObject",
    "src/modules/ResourceIdentifier.es6~ResourceIdentifierObject",
    "typedef"
  ],
  [
    "src/modules/response.es6",
    "file/src/modules/Response.es6.html",
    "src/modules/Response.es6",
    "file"
  ],
  [
    "src/modules/response.es6~errorobject",
    "typedef/index.html#static-typedef-ErrorObject",
    "src/modules/Response.es6~ErrorObject",
    "typedef"
  ],
  [
    "src/modules/response.es6~errorsourceobject",
    "typedef/index.html#static-typedef-ErrorSourceObject",
    "src/modules/Response.es6~ErrorSourceObject",
    "typedef"
  ],
  [
    "src/modules/response.es6~response#constructor",
    "class/src/modules/Response.es6~Response.html#instance-constructor-constructor",
    "src/modules/Response.es6~Response#constructor",
    "method"
  ],
  [
    "src/modules/response.es6~response#data",
    "class/src/modules/Response.es6~Response.html#instance-member-data",
    "src/modules/Response.es6~Response#data",
    "member"
  ],
  [
    "src/modules/response.es6~response#errors",
    "class/src/modules/Response.es6~Response.html#instance-member-errors",
    "src/modules/Response.es6~Response#errors",
    "member"
  ],
  [
    "src/modules/response.es6~response#headers",
    "class/src/modules/Response.es6~Response.html#instance-member-headers",
    "src/modules/Response.es6~Response#headers",
    "member"
  ],
  [
    "src/modules/response.es6~response#included",
    "class/src/modules/Response.es6~Response.html#instance-member-included",
    "src/modules/Response.es6~Response#included",
    "member"
  ],
  [
    "src/modules/response.es6~response#jqxhr",
    "class/src/modules/Response.es6~Response.html#instance-member-jqXHR",
    "src/modules/Response.es6~Response#jqXHR",
    "member"
  ],
  [
    "src/modules/response.es6~response#jsonapi",
    "class/src/modules/Response.es6~Response.html#instance-member-jsonapi",
    "src/modules/Response.es6~Response#jsonapi",
    "member"
  ],
  [
    "src/modules/response.es6~response#links",
    "class/src/modules/Response.es6~Response.html#instance-member-links",
    "src/modules/Response.es6~Response#links",
    "member"
  ],
  [
    "src/modules/response.es6~response#meta",
    "class/src/modules/Response.es6~Response.html#instance-member-meta",
    "src/modules/Response.es6~Response#meta",
    "member"
  ],
  [
    "src/modules/response.es6~response#status",
    "class/src/modules/Response.es6~Response.html#instance-member-status",
    "src/modules/Response.es6~Response#status",
    "member"
  ],
  [
    "src/modules/response.es6~jqxhr",
    "external/index.html",
    "src/modules/Response.es6~jqXHR",
    "external"
  ]
]